charged-creeper-explosion-radius: 6.0 # Настройка радиуса взрыва заряженного крипера
spawn-chance: 100.0 # Настройка шанса спавна заряженного крипера из яйца
defaultCreeperExplode: false #Может ли обычный крипер разрушать блоки в мире. false - не может, true - может
reload-message: "&aКонфигурация перезагружена"
value-message: "&cШанс должен быть между 0 и 100."
no-format-value: "&cНеверный формат числа."
